# Generated by Django 2.2.7 on 2020-02-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('money', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_account'], name='money_trans_sender__79e09e_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('base_currency', 'currency', 'date'), name='unique__base_currency__currency___date'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='money_accou_user_id_eb3353_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='unique_user_and_currency'),
        ),
    ]
